x-function-base: &base
  restart: unless-stopped
  env_file:
    - path: .env
      required: true
  command:
    - sleep
    - infinity
  profiles:
    - dev
    - prod
  user: ${CUSTOM_USER:-1000}

x-function-php: &php
  restart: unless-stopped
  user: ${CUSTOM_USER:-1000}
  build:
    dockerfile: cli.Dockerfile
    context: .docker/local/
  working_dir: /app
  environment:
    APP_NAME: "mc-manager"
  command:
    - sleep
    - infinity
  volumes:
    - ./:/app:rw
    - ./.docker/local/tests/output:/opt/phpstorm-coverage:rw
    - $HOME/.config:/home/app/.config:rw
  profiles:
    - dev
    - prod

services:
  db:
    <<: *base
    container_name: ${APP_NAME}-db
    image: mariadb:latest
    user: root
    ports:
      - "${MARIADB_PORT:-3306}:${MARIADB_PORT:-3306}"
    volumes:
      - mysql:/var/lib/mysql/
    command:
      - mariadbd
      - --port=${MARIADB_PORT:-3306}

  redis:
    <<: *base
    container_name: ${APP_NAME}-redis
    image: redis:latest
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - no
    user: root

  php:
    <<: *php
    container_name: ${APP_NAME}-php
    command:
      - sleep
      - infinity
    profiles: !override
      - dev

  node:
    <<: *base
    container_name: ${APP_NAME}-node
    image: dannypas00/node:22.11.0
    user: ${CUSTOM_USER:-1000}
    ports:
      - 5174:5174
    working_dir: /app
    command:
      - npx
      - vite
      - --host
      - --port=5174
    volumes:
      - ./:/app:rw
    profiles: !override
      - dev

  horizon:
    <<: *php
    container_name: ${APP_NAME}-horizon
    depends_on:
      - redis
      - db
    command:
      - php
      - artisan
      - horizon
    profiles:
      - dev
      - prod

  schedule:
    <<: *php
    container_name: ${APP_NAME}-schedule
    command:
      - php
      - artisan
      - schedule:work
    profiles:
      - dev
      - prod

  reverb:
    <<: *php
    container_name: ${APP_NAME}-reverb
    command:
      - php
      - artisan
      - reverb:start
      - --port=6001
      - --host=0.0.0.0
      - --debug
    ports:
      - "${REVERB_PORT:-6001}:6001"

  frank:
    <<: *php
    container_name: ${APP_NAME}-frank
    build:
      dockerfile: .docker/local/frankenphp.Dockerfile
      context: .
      args:
        USER: ${CUSTOM_USER:-app}
    depends_on:
      - reverb
    ports:
      - "${FRANKENPHP_PORT:-80}:8000"
    volumes:
      - ./:/app:rw
      - ./.docker/local/tests/output:/opt/phpstorm-coverage:rw
      - $HOME/.config:/home/app/.config:rw
      - caddy_data:/data
      - caddy_config:/config
    tty: true
    command:
      - php
      - artisan
      - octane:frankenphp
      - --watch
      - --caddyfile=/app/.docker/local/Caddyfile

  mailpit:
    <<: *base
    container_name: ${APP_NAME}-mailpit
    image: axllent/mailpit:latest
    command: [ ]
    ports:
      - "${MAILPIT_PORT:-1025}:1025"
      - "${MAILPIT_INTERFACE_PORT:-8025}:8025"

  minecraft:
    <<: *base
    container_name: ${APP_NAME}-minecraft
    image: itzg/minecraft-server:latest
    ports:
      - '25565:25565'
    user: 1000:1000
    volumes:
      - .docker/local/minecraft:/data
    restart: on-failure
    environment:
      EULA: "TRUE"
      GID: 1000
      UID: 1000
      ENABLE_ROLLING_LOGS: "true"
      RCON_PASSWORD: "test1234"
    profiles:
      - dev

  ftp:
    container_name: ${APP_NAME}-ftp
    image: delfer/alpine-ftp-server:latest
    ports:
      - '21:21'
      - '21000-21010:21000-21010'
    environment:
      - 'USERS=mcm-test|mcm-test|/minecraft|1000'
    volumes:
      - .docker/local/minecraft:/minecraft
    profiles:
      - dev

  sftp:
    container_name: ${APP_NAME}-sftp
    image: atmoz/sftp:alpine
    ports:
      - '23:22'
    environment:
      - 'SFTP_USERS=mcm-test:mcm-test:::/minecraft'
    volumes:
      - .docker/local/minecraft:/minecraft
    profiles:
      - dev

  ssh:
    container_name: ${APP_NAME}-ssh
    build:
      dockerfile: .docker/local/ssh/Dockerfile
      context: .
    ports:
      - '2222:2222'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Etc/UTC'
      - 'USER_NAME=mcm-test'
      - 'PUBLIC_KEY_FILE=/public_key'
      - 'LOG_STDOUT=true'
    volumes:
      - .docker/local/minecraft:/minecraft
      - .docker/local/public_key:/public_key
    profiles:
      - dev

volumes:
  mysql:
  caddy_data:
  caddy_config:
