/* eslint-disable */

// Generated by command, any edits will be overwritten
declare namespace App.Models {
  export interface Server {
    // columns
    id: number
    enabled: boolean
    status: ServerStatus
    port: number
    rcon_port: number
    current_players: number
    maximum_players: number
    player_list: string|null
    name: string
    description: string|null
    icon: string
    local_ip: string|null
    public_ip: string
    rcon_password: string
    created_at: Date|null
    updated_at: Date|null
    // relations
    users: Users
  }
  export type Servers = Server[]

  export interface User {
    // columns
    id: number
    name: string
    email: string
    email_verified_at: Date|null
    password?: unknown
    remember_token?: string|null
    created_at: Date|null
    updated_at: Date|null
    icon: string|null
    // relations
    servers: Servers
    tokens: PersonalAccessTokens
    notifications: DatabaseNotifications
  }
  export type Users = User[]

  const ServerStatus = {
    Unknown: 'unknown',
    Error: 'error',
    Down: 'down',
    Starting: 'starting',
    Up: 'up',
    Stopping: 'stopping',
  } as const;

  export type ServerStatus = typeof ServerStatus[keyof typeof ServerStatus]
}
