/* eslint-disable */

// Generated by command, any edits will be overwritten
declare namespace App.Models {
  export interface Server {
    // columns
    id: number
    enabled: boolean
    port: number
    rcon_port: number
    name: string
    description: string|null
    icon: string
    local_ip: string|null
    public_ip: string
    rcon_password: string
    created_at: Date|null
    updated_at: Date|null
    // relations
    users: Users
  }
  export type Servers = Server[]

  export interface User {
    // columns
    id: number
    name: string
    email: string
    email_verified_at: Date|null
    password?: unknown
    remember_token?: string|null
    created_at: Date|null
    updated_at: Date|null
    icon: string|null
    // relations
    servers: Servers
    tokens: PersonalAccessTokens
    notifications: DatabaseNotifications
  }
  export type Users = User[]
}
