version: '3'
services:
  mcm-db:
    container_name: mcm-db
    image: mariadb:latest
    ports:
      - "3306:3306"
    env_file:
      - ../../.env
    volumes:
      - ./.mysql/data:/var/lib/mysql/

  mcm-redis:
    container_name: mcm-redis
    image: redis:latest

  mcm-php:
    container_name: mcm-php
    image: dannypas00/laravel-fpm:8.2
    user: 1000:1000
    depends_on:
      - mcm-db
      - mcm-redis
    volumes:
      - ../../:/var/www

  mcm-nginx:
    container_name: mcm-nginx
    image: nginx:latest
    depends_on:
      - mcm-php
    ports:
      - "80:80"
    volumes:
      - ./nginx-includes:/etc/nginx/conf.d
      - ../../:/var/www

  mcm-minecraft:
    container_name: mcm-minecraft
    image: openjdk:22-slim
    ports:
      - "25565:25565"
      - "25575:25575"
    user: 1000:1000
    volumes:
      - ./minecraft:/minecraft
    working_dir: /minecraft
    command:
      - java
      - -Xmx512M
      - -Xms512M
      - -jar
      - server.jar
      - nogui
