services:
  base-php:
    build:
      dockerfile: cli.Dockerfile
      context: .
    environment:
      APP_NAME: "mc-manager"
    working_dir: /app
    user: ${CUSTOM_USER:-1000}
    command:
      - php
      - artisan
      - list
    volumes:
      - ../../:/app:rw
      - ./tests/output:/opt/phpstorm-coverage:rw
      - $HOME/.config:/home/app/.config:rw
      - ${NPM_CACHE_DIR:-$HOME/.npm}:/home/app/.npm:rw
      - ${COMPOSER_CACHE:-$HOME/.cache/composer}:/home/app/.cache:rw
